openapi:
  secretKey: AdhX8vuZ16gYBNKz1wACLxzXAanfwZHpPKNoJ3n4e7qvEXZxa9XZKH8H4tU6plPJ0DiNEbi9A15W4VZf6pq6lQ==
  dataType: json
  timeout: 5
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
